app/blueprints/insights/__init__.py
# app/blueprints/insights/__init__.py
from . import routes

insights_bp = routes.insights_bp

app/blueprints/insights/routes.py
# app/blueprints/insights/routes.py
import requests
from flask import Blueprint, render_template
from flask_login import current_user, login_required

from .helpers import _get, get_top_tracks

insights_bp = Blueprint("insights", __name__)


@insights_bp.route("/insights")
@login_required
def home():
    """Retrieve the user's top tracks from the songswap-insights API"""

    # Get the user's ID from the session
    user_id = current_user.id

    # Get the response data as JSON
    data = get_top_tracks(user_id)

    # Convert data['duration_ms'] to minutes and seconds
    for track in data:
        track[
            "duration_str"
        ] = f"{track['duration_ms'] // 60000}:{(track['duration_ms'] % 60000) // 1000:02}"

    # Render the template with the data
    return render_template("insights.html", tracks=data)


@insights_bp.route("/insights_global")
@login_required
def home_global():
    """Retrieve total and distinct statistics from songswap-insights API"""

    total_tracks_json = _get("/insights/global/total/listens", as_json=True)
    distinct_tracks_json = _get("/insights/global/distinct/tracks", as_json=True)
    distinct_artists_json = _get(
        "/insights/global/distinct/primary-artists", as_json=True
    )
    total_listen_time = _get(
        "/insights/global/total/listen-time",
        params={"as_string": True},
    )

    top_tracks_json = _get(
        "/insights/global/top/tracks",
        params={"limit": 10},
        as_json=True,
    )
    top_artists_json = _get(
        "/insights/global/top/artists",
        params={"limit": 10},
        as_json=True,
    )

    track_names = [track["track_name"] for track in top_tracks_json]
    artist_names = [track["artist_name"] for track in top_tracks_json]
    track_counts = [track["count"] for track in top_tracks_json]

    top_tracks = [
        {"track_name": track_name, "artist_name": artist_name, "count": count}
        for track_name, artist_name, count in zip(
            track_names, artist_names, track_counts
        )
    ]
    top_artists = [
        {"artist_name": artist["artist_name"], "count": artist["count"]}
        for artist in top_artists_json
    ]

    return render_template(
        "insights_global.html",
        total_tracks=total_tracks_json,
        distinct_tracks=distinct_tracks_json,
        distinct_artists=distinct_artists_json,
        total_listen_time=total_listen_time.content.decode("utf-8").replace('"', ""),
        top_tracks=top_tracks,
        top_artists=top_artists,
    )

app/templates/auth_home.html
{% extends "base.html" %}

{% block content %}
<!-- An authenticated homepage written using Bulma CSS -->
<section class="hero is-dark is-fullheight">
    <!-- Welcome the user specifically -->

    <div class="hero-body">
        <div class="container has-text-centered">  <!-- Centered text in the container -->
            <h1 class="title">
                Welcome to SongSwap!
            </h1>
            <h2 class="subtitle">
                This is the authenticated homepage.
            </h2>
            <p>
                Welcome, {{ current_user.username }}!
            </p>
        </div>
    </div>

</section>

{% endblock %}

app/templates/base.html
<!-- app/templates/base.html -->
<!doctype html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="UTF-8">
    <title>SongSwap</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    {% block styles %}{% endblock %}
</head>

<body>
    {% include 'navbar.html' %}

    <section class="section hero is-dark is-fullheight-with-navbar">

        <div class="container">
            <!-- Flash message handling -->
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="notification is-{{ category }}">
                            <button class="delete"></button>
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {% block content %}{% endblock %}
        </div>
    </section>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        // Make the Bulma flash messages dismissible
        document.addEventListener('DOMContentLoaded', () => {
            (document.querySelectorAll('.notification .delete') || []).forEach(($delete) => {
                const $notification = $delete.parentNode;

                $delete.addEventListener('click', () => {
                    $notification.parentNode.removeChild($notification);
                });
            });
        });
    </script>
    {% block scripts %}{% endblock %}
</body>

</html>

app/templates/insights.html
<!-- app/templates/insights.html -->
{% extends "base.html" %}

{% block content %}
<section class="container" id="playlist">
    <section class="columns">
        <div class="column">
            <div class="box content">
                <p class="heading has-text-centered">Top 10 Tracks</p>
                <table id="top-tracks">
                    <thead>
                        <tr>
                            <th>Rank</th>
                            <th>Track</th>
                            <th>Plays</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for track in tracks %}
                            <tr>
                                <td style="text-align:center; vertical-align:middle;font-weight:bold;">{{ loop.index }}</td>
                                <td>
                                    <div class="level">
                                        <div class="level-item level-left list-item-image" style="max-width:fit-content;">
                                            <figure class="image is-64x64" style="margin-left:0;margin-right:0;">
                                                <img src="{{ track.image_url }}"
                                                    alt="Track Image of {{ track.track_name }} by {{ track.artist_name }}">
                                            </figure>
                                        </div>

                                        <div class="level-item list-item-content" style="align-items:start;">
                                            <div class="list-item-title" style="text-overflow:ellipsis;">
                                                {{ track.track_name }}
                                            </div>

                                            <div class="description">
                                                {{ track.artist_name }} · {{ track.duration_str }}
                                            </div>
                                        </div>

                                        <div class="level-item level-right list-item-controls">
                                            <div class="buttons">
                                                <!-- Unique id for each track's preview button -->
                                                <button id="playButton{{ track.track_id }}"
                                                    class="button is-small is-light is-hidden-mobile">
                                                    <span class="icon">
                                                        <i class="fa fa-play"></i>
                                                    </span>
                                                </button>

                                                <button class="button is-small is-light">
                                                    <span class="icon">
                                                        <i class="fa fa-ellipsis-v"></i>
                                                    </span>
                                                </button>
                                                <!-- Audio tag for track preview -->
                                                <audio id="audio{{ track.track_id }}" src="{{ track.preview_url }}"
                                                    style="display: none;"></audio>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                                <td style="text-align:center; vertical-align:middle;">{{ track.count }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>

    <div class="modal" id="myModal">
        <div class="modal-background"></div>
        <div class="modal-content">
            <!-- Any other Bulma elements you want -->
        </div>
        <button class="modal-close is-large" aria-label="close"></button>
    </div>
</section>
{% endblock %}

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script>
    function togglePlay(audio, button) {
        if (audio.paused) {
            audio.play();
            button.innerHTML = '<span class="icon"><i class="fa fa-pause"></i></span>';
        } else {
            audio.pause();
            button.innerHTML = '<span class="icon"><i class="fa fa-play"></i></span>';
        }
    }

    {% for track in tracks %}
        (function () {
            var trackId = "{{ track.track_id }}";
            var audio = document.getElementById('audio' + trackId);
            var button = document.getElementById('playButton' + trackId);

            button.addEventListener('click', function () {
                togglePlay(audio, button);
            });
        })();
    {% endfor %}


    document.getElementById('openModalButton').addEventListener('click', function () {
        document.getElementById('myModal').classList.add('is-active');
    });

    document.querySelector('.modal-close').addEventListener('click', function () {
        document.getElementById('myModal').classList.remove('is-active');
    });
</script>

<!-- {% endblock %}

    {% for track in tracks %}
        var trackId = "{{ track.track_id }}";
        var audio = document.getElementById('audio' + trackId);
        var button = document.getElementById('playButton' + trackId);

        button.addEventListener('click', function () {
            togglePlay(audio, button);
        });
    {% endfor %} -->

app/templates/insights_global.html
<!-- app/templates/insights_global.html -->
{% extends "base.html" %}
{% block content %}
<!-- Begin Row#1 -->
<!-- Col#1: Total number of tracks listened to for all users -->
<div class="hero-head">
    <section class="container">
        <h1 class="title">
            Global Insights
        </h1>
        <div class="hero-body">
            <h2 class="subtitle">
                Here are some insights about all users.
            </h2>
        </div>
    </section>
</div>

<section class="container justify-content is-justify-content-space-evenly ">
    <!-- Begin Row#1 -->
    <section class="info-tiles is-fluid ">
        <div class="tile is-ancestor has-text-centered ">
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <p class="heading">Total Listens</p>
                    <p class="title has-text-primary">{{ total_tracks }}</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <p class="heading">Unique Tracks</p>
                    <p class="title has-text-primary">{{ distinct_tracks }}</p>
                </article>
            </div>
            <div class="tile is-parent">
                <article class="tile is-child box">
                    <p class="heading">Unique Artists</p>
                    <p class="title has-text-primary">{{ distinct_artists }}</p>
                </article>
            </div>
            <div class="tile is-parent is-flex-grow-2">
                <article class="tile is-child box">
                    <p class="heading">Total Listen
                        Duration</p>
                    <p class="title has-text-primary">{{ total_listen_time }}</p>
                </article>
            </div>
        </div>
    </section>

    <section class="columns is-fluid">
        <!-- Top 10 Artists -->
        <div class="column is-4">
            <div class="box content is-fullheight">
                <p class="heading has-text-centered">Top 10 Artists</p>
                <table id="top_artists">
                    <thead>
                        <tr>
                            <th>Artist</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for artist in top_artists %}
                        <tr>
                            <td>{{ artist.artist_name }}</td>
                            <td>{{ artist.count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="column is-8">
            <div class="box content">
                <p class="heading has-text-centered">Top 10 Tracks</p>
                <table id="top-tracks">
                    <thead>
                        <tr>
                            <th>Artist</th>
                            <th>Track</th>
                            <th>Count</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for track in top_tracks %}
                        <tr>
                            <td>{{ track.artist_name }}</td>
                            <td>{{ track.track_name }}</td>
                            <td>{{ track.count }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </section>
</section>


{% endblock %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/echarts@5.4.2/dist/echarts.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
{% endblock %}

app/templates/navbar.html
<nav class="navbar is-light" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{{ url_for('auth.home') }}">
            <img src="path-to-your-logo" alt="SongSwap">
        </a>
    </div>

    <div class="navbar-menu">
        <div class="navbar-start">
            {% if current_user.is_authenticated %}

            <a class="navbar-item" href="{{ url_for('auth.home') }}">
                <div>
                    <span class="icon">
                        <i class="fa fa-users"></i>
                    </span>
                    Groups
                </div>
            </a>
            <a class="navbar-item" href="{{ url_for('insights.home') }}">
                <div>
                    <span class="icon">
                        <i class="fa fa-area-chart"></i>
                    </span>
                    Insights
                </div>
            </a>
            {% endif %}
        </div>

        <div class="navbar-end">
            {% if not current_user.is_authenticated %}
            <a class="navbar-item" href="{{ url_for('auth.home') }}">Login</a>
            {% else %}
            <div class="navbar-item has-dropdown is-hoverable is-transparent">
                <div class="navbar-link">
                    {{ current_user.username }}
                </div>
                <div class="navbar-dropdown is-right">
                    <a class="navbar-item" href="{{ url_for('auth.home') }}">
                        <div>
                            <span class="icon">
                                <i class="fa fa-user-circle-o"></i>
                            </span>
                            Profile
                        </div>
                    </a>
                    <a class="navbar-item" href="{{ url_for('auth.home') }}">
                        <div>
                            <span class="icon">
                                <i class="fa fa-cog"></i>
                            </span>
                            Account
                        </div>
                    </a>

                    <hr class="navbar-divider">

                    <a class="navbar-item" href="{{ url_for('auth.home') }}">
                        <div>
                            <span class="icon">
                                <i class="fa fa-bug"></i>
                            </span>
                            Report Bug
                        </div>
                    </a>

                    <hr class="navbar-divider">

                    <a class="navbar-item" href="{{ url_for('auth.logout') }}">
                        <div>
                            <span class="icon">
                                <i class="fa fa-sign-out"></i>
                            </span>
                            Sign Out
                        </div>
                    </a>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
</nav>

app/templates/register.html
{% extends "base.html" %}
{% block content %}
  <h1>Register</h1>
  <form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
      {{ form.username.label }}<br>
      {{ form.username(size=32) }}
    </p>
    <p>
      {{ form.email.label }}<br>
      {{ form.email(size=32) }}
    </p>
    <p>{{ form.submit() }}</p>
  </form>
{% endblock %}

app/templates/unauth_home.html
{% extends "base.html" %}

{% block content %}
<div class="column is-half is-offset-one-quarter text-center">
    <h1>SongSwap</h1>
    <p>Share and discover music with your friends.</p>
    <a class="button" href="{{ spotify_auth_url }}">Login with Spotify</a>
</div>
{% endblock %}